INFO     http.client:base_api.py:17 Making GET request to URL: http://localhost:4001/users
INFO     http.client:base_api.py:21 Request Headers:
{
    "Authorization": "Bearer bad_token_value"
}
INFO     http.client:base_api.py:38 Response Status Code: 403
INFO     http.client:base_api.py:41 Response Headers:
{
    "Vary": "Origin, Access-Control-Request-Method, Access-Control-Request-Headers",
    "X-Content-Type-Options": "nosniff",
    "X-XSS-Protection": "1; mode=block",
    "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",
    "Pragma": "no-cache",
    "Expires": "0",
    "X-Frame-Options": "DENY",
    "Content-Length": "0",
    "Date": "Wed, 12 Jun 2024 19:23:55 GMT",
    "Keep-Alive": "timeout=60",
    "Connection": "keep-alive"
}